#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "evcc"
name = "EVCC"
description.en = "Create a redirection or a proxy to another path"
description.fr = "Créer une redirection ou un proxy vers un autre emplacement"

version = "0.303.1~ynh2.1"

maintainers = ['Didier Chavaroche']

[upstream]
license = "AGPL-3.0-or-later"
website = "https://evcc.io/"

[integration]
yunohost = ">= 11.2.30"
helpers_version = "2.1"
architectures = "all"
multi_instance = true
ldap = "not_relevant"
sso = "not_relevant"
disk = "100M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.apt]
    packages_from_raw_bash = """
        curl -1sLf 'https://dl.evcc.io/public/evcc/stable/setup.deb.sh' | sudo -E bash > /dev/null 2>&1
        apt update > /dev/null 2>&1
        echo evcc
    """
    
    [resources.system_user]

    [resources.permissions]
    main.url = "/"
    main.auth_header = false

    [resources.ports]
    remote_http.default = 7070
    remote_http.exposed = "TCP"
    remote_ws.default = 8887
    remote_ws.exposed = "TCP"
    remote_wss.default = 8888
    remote_wss.exposed = "TCP"