#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INSTALL EVCC
#=================================================
ynh_setup_source --dest_dir="/opt/" --source_id="main"

#=================================================
# CONFIGURE SERVICE
#=================================================

ynh_systemctl --action="start" --log_path="/var/log/evcc.log"

#=================================================
# CONFIGURE NGINX
#=================================================
ynh_script_progression "Configuring NGINX web server..."

ynh_config_add_nginx

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
