#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# START SERVICE
#=================================================
ynh_script_progression "Adding EVCC configuration..."

ynh_config_add --template="evcc.yaml" --destination="/etc/evcc.yaml"

#=================================================
# CONFIGURE NGINX
#=================================================
ynh_script_progression "Configuring NGINX web server..."

ynh_config_add_nginx

#=================================================
# START SERVICE
#=================================================

ynh_systemctl --action="restart" --timeout=600 --log_path=systemd
yunohost service add evcc

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
