#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# START SERVICE
#=================================================

ynh_systemctl --action="start" --wait_until="server is serve on http://127.0.0.1" --log_path=systemd

#=================================================
# CONFIGURE NGINX
#=================================================
ynh_script_progression "Configuring NGINX web server..."

ynh_config_add_nginx

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
