#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers


#=================================================
# CONFIGURE NGINX
#=================================================
ynh_script_progression "Configuring NGINX web server..."


ynh_config_add_nginx

ynh_script_progression "Upgrade of $app completed"
